datasets:
  text_vqa:
    # data_dir: ${env.data_dir}/datasets
    data_type: images 
    build_info:
      # Be careful not to append minus sign (-) before split to avoid itemizing
      annotations:
        train:
          url:
              - https://drive.google.com/u/0/uc?id=1-2InrtIy2hq8MjqoLe2oXPTCbnVx52Ue
              # - https://drive.google.com/u/0/uc?id=1Gi_DzomI9JKEHObzRtCjNlc699HlcZMG
          storage:
              - textvqa/annotations/textvqa_train.json
        val:
          url:
              - https://drive.google.com/u/0/uc?id=1u-3nbS-hLNDKvFSfJbDVXnumBqJwfdtB
              # - https://drive.google.com/u/0/uc?id=1-6i7x4Au6wngeYvMYHaOWrpUMOuWNwQM
              - https://drive.google.com/u/0/uc?id=1-pFhw6IUnIi_0Yh5zA63jzawFaUB4d-i
          storage:
              - textvqa/annotations/textvqa_val.json
              - textvqa/annotations/answer_list.json
      images:
          storage: textvqa/images/
